version: '3.2'
services:
  server:
    build:
      context: .
    ports:
      - "8000:80"
    volumes:
      - "./asset-mgmt:/var/www/html/"
  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=assetmgmt"
    volumes:
      - "./dbinit-scripts:/docker-entrypoint-initdb.d"